### ISSUE TITLE
SkQuery 4.1.7 does not load

### ISSUE THREAD

**Issue by iRaphi05** [SkQuery/SkQuery#115]
**Describe the bug**
SkQuery 4.1.7 does not load on my Server, im getting the following error:
[18:43:18 ERROR]: Error occurred while enabling SkQuery v4.1.7 (Is it up to date?)
java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
        at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:220) ~[SkQuery-4.1.7.jar:?]
        at org.bstats.MetricsBase.<init>(MetricsBase.java:104) ~[SkQuery-4.1.7.jar:?]
        at org.bstats.bukkit.Metrics.<init>(Metrics.java:74) ~[SkQuery-4.1.7.jar:?]
        at com.w00tmast3r.skquery.SkQuery.onEnable(SkQuery.java:35) ~[SkQuery-4.1.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-58]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-58]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-58]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**To Reproduce**
Just load SkQuery 4.1.7 on a Paper 1.19 server.

**Information:**

Skript version: Skript 2.6.3
Server software: Paper
Server version: git-Paper-58 (MC: 1.19)

**Additional context**
bStats is disabled on the server

**Comment by TheLimeGlass** [comment]
Redownload the plugin

**Comment by iRaphi05** [comment]
Did not fix it...

**Comment by MisterLolxd2** [comment]
https://github.com/SkQuery/SkQuery/issues/114 same.

**Comment by madebygood** [comment]
same problem. 
4.1.7 can not load

**Comment by naunaud84820** [comment]
Same here

**Comment by TheLimeGlass** [comment]
Redownload the plugin. The plugin still works fine.
