### ISSUE TITLE
Problem with $ thread

### ISSUE THREAD

**Issue by Envizar** [SkQuery/SkQuery#125]
**All version information in error, lastest SkQuery**
Posting here cuz function executed with `$ thread` from skquery
```
[18:36:42 ERROR]: #!#! 
[18:36:42 ERROR]: #!#! [Skript] Severe Error:
[18:36:42 ERROR]: #!#! 
[18:36:42 ERROR]: #!#! Something went horribly wrong with Skript.
[18:36:42 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[18:36:42 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[18:36:42 ERROR]: #!#! Following plugins are probably related to this error in some way:
[18:36:42 ERROR]: #!#! SkQuery 
[18:36:42 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[18:36:42 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[18:36:42 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[18:36:42 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[18:36:42 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[18:36:42 ERROR]: #!#! 
[18:36:42 ERROR]: #!#! Stack trace:
[18:36:42 ERROR]: #!#! java.util.ConcurrentModificationException
[18:36:42 ERROR]: #!#!     at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[18:36:42 ERROR]: #!#!     at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[18:36:42 ERROR]: #!#!     at net.minecraft.server.level.WorldServer.sendParticles(WorldServer.java:1868)
[18:36:42 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.spawnParticle(CraftWorld.java:2077)
[18:36:42 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.spawnParticle(CraftWorld.java:2070)
[18:36:42 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.spawnParticle(CraftWorld.java:2064)
[18:36:42 ERROR]: #!#!     at SkBee-2.5.0.jar//com.shanebeestudios.skbee.api.particle.ParticleUtil.spawnParticle(ParticleUtil.java:144)
[18:36:42 ERROR]: #!#!     at SkBee-2.5.0.jar//com.shanebeestudios.skbee.elements.other.effects.EffParticle.execute(EffParticle.java:96)
[18:36:42 ERROR]: #!#!     at Skript (11).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[18:36:42 ERROR]: #!#!     at Skript (11).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[18:36:42 ERROR]: #!#!     at Skript (11).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[18:36:42 ERROR]: #!#!     at Skript (11).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[18:36:42 ERROR]: #!#!     at Skript (11).jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[18:36:42 ERROR]: #!#!     at Skript (11).jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[18:36:42 ERROR]: #!#!     at Skript (11).jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:288)
[18:36:42 ERROR]: #!#!     at Skript (11).jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[18:36:42 ERROR]: #!#!     at Skript (11).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[18:36:42 ERROR]: #!#!     at Skript (11).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[18:36:42 ERROR]: #!#!     at jdk.internal.reflect.GeneratedMethodAccessor174.invoke(Unknown Source)
[18:36:42 ERROR]: #!#!     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:36:42 ERROR]: #!#!     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:36:42 ERROR]: #!#!     at SkQuery-4.1.7.jar//com.w00tmast3r.skquery.elements.effects.EffOptionThread$2.call(EffOptionThread.java:62)
[18:36:42 ERROR]: #!#!     at SkQuery-4.1.7.jar//com.w00tmast3r.skquery.elements.effects.EffOptionThread$2.call(EffOptionThread.java:59)
[18:36:42 ERROR]: #!#!     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[18:36:42 ERROR]: #!#!     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:36:42 ERROR]: #!#!     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:36:42 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[18:36:42 ERROR]: #!#! 
[18:36:42 ERROR]: #!#! Version Information:
[18:36:42 ERROR]: #!#!   Skript: 2.6.3 (latest)
[18:36:42 ERROR]: #!#!     Flavor: skriptlang-github
[18:36:42 ERROR]: #!#!     Date: 00:55:22.847925631
[18:36:42 ERROR]: #!#!   Bukkit: 1.19.2-R0.1-SNAPSHOT
[18:36:42 ERROR]: #!#!   Minecraft: 1.19.2
[18:36:42 ERROR]: #!#!   Java: 17.0.2 (OpenJDK 64-Bit Server VM 17.0.2+8-86)
[18:36:42 ERROR]: #!#!   OS: Linux amd64 5.4.0-125-generic
[18:36:42 ERROR]: #!#! 
[18:36:42 ERROR]: #!#! Server platform: Paper
[18:36:42 ERROR]: #!#! 
[18:36:42 ERROR]: #!#! Current node: null
[18:36:42 ERROR]: #!#! Current item: draw [[long:5]] of [[particle:dust_color_transition]] using {_effect} (as java.lang.Object) at the location of {_st} (as org.bukkit.Location) with offset vector([[double:0.1]], [[double:0.1]], [[double:0.1]]) with extra [[long:1]] 
[18:36:42 ERROR]: #!#! Current trigger: function draw1 (simple event) (event.sk, line 28)
[18:36:42 ERROR]: #!#! 
[18:36:42 ERROR]: #!#! Thread: pool-109-thread-7
[18:36:42 ERROR]: #!#! 
[18:36:42 ERROR]: #!#! Language: english
[18:36:42 ERROR]: #!#! Link parse mode: DISABLED
[18:36:42 ERROR]: #!#! 
[18:36:42 ERROR]: #!#! End of Error.
[18:36:42 ERROR]: #!#!
```

**Comment by TheLimeGlass** [comment]
Thread is designed for SQL tasks, please don't use it for particles based on the error.
