### ISSUE TITLE
SkQuery turns off

### ISSUE THREAD

**Issue by MisterLolxd2** [SkQuery/SkQuery#127]
**Describe the bug**
Skquery turns off on server start, reason i sends below.

**Information:**
- Skript version: 2.6.4
- SkQuery version: 4.1.8
- Java: 17
- Server software: Purpur
- Server version: 1.16.5

**Additional context**
[16:00:22] [Server thread/INFO]: [SkQuery] Enabling SkQuery v4.1.8
[16:00:22] [Server thread/INFO]: [skQuery] Locating classes from SkQuery...
[16:00:22] [Server thread/INFO]: [skQuery] Beginning to process a total of 120 from SkQuery
[16:00:22] [Server thread/INFO]: [skQuery] Out of 120 classes, 120 classes were loaded from SkQuery
[16:00:22] [Server thread/ERROR]: Error occurred while enabling SkQuery v4.1.8 (Is it up to date?)
java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
	at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:220) ~[?:?]
	at org.bstats.MetricsBase.<init>(MetricsBase.java:104) ~[?:?]
	at org.bstats.bukkit.Metrics.<init>(Metrics.java:74) ~[?:?]
	at com.w00tmast3r.skquery.SkQuery.onEnable(SkQuery.java:35) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[16:00:22] [Server thread/INFO]: [SkQuery] Disabling SkQuery v4.1.8

**Comment by TheLimeGlass** [comment]
Fixed, redownload the jar.
