### ISSUE TITLE
SkQuery fails to start on Paper 1.19.3

### ISSUE THREAD

**Issue by takatalvi** [SkQuery/SkQuery#128]
**Describe the bug**
Latest SkQuery gives an exception on server startup and fails to get enabled.

**To Reproduce**
Run a clean Paper server (1.19.3 build 334) with no plugins other than Skript and SkQuery. The plugins will be loaded but SkQuery gives an exception:
```
[15:59:54] [Server thread/INFO]: [SkQuery] Enabling SkQuery v4.1.8
[15:59:54] [Server thread/INFO]: [skQuery] Locating classes from SkQuery...
[15:59:54] [Server thread/INFO]: [skQuery] Beginning to process a total of 120 from SkQuery
[15:59:54] [Server thread/INFO]: [skQuery] Out of 120 classes, 120 classes were loaded from SkQuery
[15:59:54] [Server thread/ERROR]: Error occurred while enabling SkQuery v4.1.8 (Is it up to date?)
java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
	at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:220) ~[SkQuery-4.1.8.jar:?]
	at org.bstats.MetricsBase.<init>(MetricsBase.java:104) ~[SkQuery-4.1.8.jar:?]
	at org.bstats.bukkit.Metrics.<init>(Metrics.java:74) ~[SkQuery-4.1.8.jar:?]
	at com.w00tmast3r.skquery.SkQuery.onEnable(SkQuery.java:35) ~[SkQuery-4.1.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-334]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-334]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-334]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-334]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-334]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-334]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-334]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:59:54] [Server thread/INFO]: [SkQuery] Disabling SkQuery v4.1.8
```

**Information:**
- Skript version: v2.6.4
- Server software: Paper 1.19.3 build 334
- Server version: 1.19.3

**Additional context**
```
Full server startup log:
[15:59:40] [ServerMain/INFO]: Building unoptimized datafixer
[15:59:42] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:59:44] [ServerMain/INFO]: Loaded 7 recipes
[15:59:45] [Server thread/INFO]: Starting minecraft server version 1.19.3
[15:59:45] [Server thread/INFO]: Loading properties
[15:59:45] [Server thread/INFO]: This server is running Paper version git-Paper-334 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 20503be)
[15:59:45] [Server thread/INFO]: Server Ping Player Sample Count: 10
[15:59:45] [Server thread/INFO]: Using 4 threads for Netty based IO
[15:59:45] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[15:59:45] [Server thread/INFO]: Default game type: SURVIVAL
[15:59:45] [Server thread/INFO]: Generating keypair
[15:59:45] [Server thread/INFO]: Starting Minecraft server on *:25565
[15:59:45] [Server thread/INFO]: Using default channel type
[15:59:45] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[15:59:45] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[15:59:46] [Server thread/INFO]: [Skript] Loading Skript v2.6.4
[15:59:46] [Server thread/INFO]: [SkQuery] Loading SkQuery v4.1.8
[15:59:46] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:59:46] [Server thread/INFO]: Preparing level "world"
[15:59:46] [Server thread/INFO]: -------- World Settings For [world] --------
[15:59:46] [Server thread/INFO]: Mob Spawn Range: 6
[15:59:46] [Server thread/INFO]: Experience Merge Radius: 4.0
[15:59:46] [Server thread/INFO]: Cactus Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: Cane Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: Melon Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: Sapling Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: Carrot Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: Potato Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: Wheat Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: Vine Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: Kelp Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: GlowBerry Growth Modifier: 100%
[15:59:46] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 24 / Tiv false / Isa false
[15:59:46] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[15:59:46] [Server thread/INFO]: Entity Tracking Range: Pl 64 / An 48 / Mo 48 / Mi 32 / Other 64
[15:59:46] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1 Hopper Can Load Chunks: false
[15:59:46] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[15:59:46] [Server thread/INFO]: Max TNT Explosions: 100
[15:59:46] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[15:59:46] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[15:59:46] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[15:59:46] [Server thread/INFO]: View Distance: 10
[15:59:46] [Server thread/INFO]: Simulation Distance: 10
[15:59:46] [Server thread/INFO]: Item Merge Radius: 4.0
[15:59:46] [Server thread/INFO]: Item Despawn Rate: 6000
[15:59:46] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[15:59:47] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[15:59:47] [Server thread/INFO]: Mob Spawn Range: 6
[15:59:47] [Server thread/INFO]: Experience Merge Radius: 4.0
[15:59:47] [Server thread/INFO]: Cactus Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Cane Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Melon Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Sapling Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Carrot Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Potato Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Wheat Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Vine Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Kelp Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: GlowBerry Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 24 / Tiv false / Isa false
[15:59:47] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[15:59:47] [Server thread/INFO]: Entity Tracking Range: Pl 64 / An 48 / Mo 48 / Mi 32 / Other 64
[15:59:47] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1 Hopper Can Load Chunks: false
[15:59:47] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[15:59:47] [Server thread/INFO]: Max TNT Explosions: 100
[15:59:47] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[15:59:47] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[15:59:47] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[15:59:47] [Server thread/INFO]: View Distance: 10
[15:59:47] [Server thread/INFO]: Simulation Distance: 10
[15:59:47] [Server thread/INFO]: Item Merge Radius: 4.0
[15:59:47] [Server thread/INFO]: Item Despawn Rate: 6000
[15:59:47] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[15:59:47] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[15:59:47] [Server thread/INFO]: Mob Spawn Range: 6
[15:59:47] [Server thread/INFO]: Experience Merge Radius: 4.0
[15:59:47] [Server thread/INFO]: Cactus Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Cane Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Melon Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Sapling Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Carrot Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Potato Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Wheat Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Vine Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Kelp Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: GlowBerry Growth Modifier: 100%
[15:59:47] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 24 / Tiv false / Isa false
[15:59:47] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[15:59:47] [Server thread/INFO]: Entity Tracking Range: Pl 64 / An 48 / Mo 48 / Mi 32 / Other 64
[15:59:47] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1 Hopper Can Load Chunks: false
[15:59:47] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[15:59:47] [Server thread/INFO]: Max TNT Explosions: 100
[15:59:47] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[15:59:47] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[15:59:47] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[15:59:47] [Server thread/INFO]: View Distance: 10
[15:59:47] [Server thread/INFO]: Simulation Distance: 10
[15:59:47] [Server thread/INFO]: Item Merge Radius: 4.0
[15:59:47] [Server thread/INFO]: Item Despawn Rate: 6000
[15:59:47] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[15:59:47] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[15:59:47] [Server thread/INFO]: Time elapsed: 100 ms
[15:59:47] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[15:59:47] [Server thread/INFO]: Time elapsed: 25 ms
[15:59:47] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[15:59:47] [Server thread/INFO]: Time elapsed: 20 ms
[15:59:47] [Server thread/INFO]: [Skript] Enabling Skript v2.6.4
[15:59:47] [Server thread/INFO]: [Skript] Skript's language file english.lang is outdated, some messages will be english.
[15:59:48] [ForkJoinPool.commonPool-worker-1/INFO]: [Skript] You're currently running the latest stable version of Skript.
[15:59:53] [Server thread/INFO]: [Skript] Loaded 153613 aliases in 5699ms
[15:59:54] [Server thread/INFO]: [Skript]  ~ created by & © Peter Güttinger aka Njol ~
[15:59:54] [Server thread/INFO]: [SkQuery] Enabling SkQuery v4.1.8
[15:59:54] [Server thread/INFO]: [skQuery] Locating classes from SkQuery...
[15:59:54] [Server thread/INFO]: [skQuery] Beginning to process a total of 120 from SkQuery
[15:59:54] [Server thread/INFO]: [skQuery] Out of 120 classes, 120 classes were loaded from SkQuery
[15:59:54] [Server thread/ERROR]: Error occurred while enabling SkQuery v4.1.8 (Is it up to date?)
java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
	at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:220) ~[SkQuery-4.1.8.jar:?]
	at org.bstats.MetricsBase.<init>(MetricsBase.java:104) ~[SkQuery-4.1.8.jar:?]
	at org.bstats.bukkit.Metrics.<init>(Metrics.java:74) ~[SkQuery-4.1.8.jar:?]
	at com.w00tmast3r.skquery.SkQuery.onEnable(SkQuery.java:35) ~[SkQuery-4.1.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-334]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-334]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-334]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-334]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-334]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-334]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-334]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:59:54] [Server thread/INFO]: [SkQuery] Disabling SkQuery v4.1.8
[15:59:54] [Server thread/INFO]: Running delayed init tasks
[15:59:54] [Server thread/INFO]: [Skript] Loading variables...
[15:59:54] [Server thread/INFO]: [Skript] Loaded 0 variables in 0.0 seconds
[15:59:54] [Server thread/INFO]: [Skript] All scripts loaded without errors.
[15:59:54] [Server thread/INFO]: [Skript] Loaded 1 script with a total of 1 trigger and 0 commands in 0.03 seconds
[15:59:54] [Server thread/INFO]: [Skript] Finished loading.
[15:59:54] [Server thread/INFO]: Done (9.221s)! For help, type "help"
[15:59:54] [Server thread/INFO]: Timings Reset
[15:59:57] [Server thread/INFO]: Checking version, please wait...
[15:59:57] [Thread-6/INFO]: This server is running Paper version git-Paper-334 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 20503be)
You are running the latest version
Previous version: git-Paper-263 (MC: 1.19.2)
```

**Comment by TheLimeGlass** [comment]
Fixed, redownload the jar.

**Comment by takatalvi** [comment]
It's fixed, thank you!
