### ISSUE TITLE
Paper is not working

### ISSUE THREAD

**Issue by kimidake** [SkQuery/SkQuery#136]
[14:51:16 ERROR]: Error occurred while enabling SkQuery v4.1.8 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at io.papermc.paper.plugin.manager.DummyBukkitPluginLoader.getPluginDescription(DummyBukkitPluginLoader.java:35) ~[paper-1.19.3.jar:git-Paper-425]
        at com.w00tmast3r.skquery.Registration.enableSnooper(Registration.java:42) ~[SkQuery-4.1.8.jar:?]
        at com.w00tmast3r.skquery.SkQuery.onEnable(SkQuery.java:33) ~[SkQuery-4.1.8.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-425]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-425]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.3.jar:git-Paper-425]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:472) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-425]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[14:51:16 INFO]: [SkQuery] Disabling SkQuery v4.1.8
[14:51:16 ERROR]: Error occurred (in the plugin loader) while disabling SkQuery v4.1.8 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.w00tmast3r.skquery.SkQuery.onDisable(SkQuery.java:45) ~[SkQuery-4.1.8.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[paper-1.19.3.jar:git-Paper-425]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.19.3.jar:git-Paper-425]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:196) ~[paper-1.19.3.jar:git-Paper-425]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-425]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.3.jar:git-Paper-425]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:472) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-425]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[paper-1.19.3.jar:git-Paper-425]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227) ~[paper-1.19.3.jar:git-Paper-425]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[paper-1.19.3.jar:git-Paper-425]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:207) ~[paper-1.19.3.jar:git-Paper-425]
        at com.w00tmast3r.skquery.elements.events.EvtLambdaWhen.<clinit>(EvtLambdaWhen.java:24) ~[SkQuery-4.1.8.jar:?]
        ... 16 more

**Comment by AuthenTiiq** [comment]
Same problem on last Paper version

**Comment by lis0** [comment]
working on 1.19 but not on 1.19.3

**Comment by NoxWilding** [comment]
I'm facing a similar issue with the Paper version git-Paper416 (1.19.3)

**Comment by MrY3llow** [comment]
I have the same issue

**Comment by MrY3llow** [comment]
Version paper : 1.19.3-412
List of my plugins : https://drive.google.com/drive/folders/1MlP5Ra05sxD8QmfyJ6PwVx68J6lDOOkf?usp=sharing

**Comment by TheLimeGlass** [comment]
duplicate https://github.com/SkQuery/SkQuery/issues/132
