### ISSUE TITLE
Error While Enabling And Disabling

### ISSUE THREAD

**Issue by GuavaGivki** [SkQuery/SkQuery#141]
**Server**: Purpur 1.19.3
**Skript Version**: 2.6.4
**Addon**: SkBee, skript-placeholders, skript-reflect, DiSky, WebSK
**Java**: 17

Error Log:

```[12:12:02] [Server thread/INFO]: [SkQuery] Enabling SkQuery v4.1.8
[12:12:02] [Server thread/ERROR]: Error occurred while enabling SkQuery v4.1.8 (Is it up to date?)
java.lang.UnsupportedOperationException: null
	at io.papermc.paper.plugin.manager.DummyBukkitPluginLoader.getPluginDescription(DummyBukkitPluginLoader.java:35) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at com.w00tmast3r.skquery.Registration.enableSnooper(Registration.java:42) ~[SkQuery-4.1.8.jar:?]
	at com.w00tmast3r.skquery.SkQuery.onEnable(SkQuery.java:33) ~[SkQuery-4.1.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:574) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:485) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:12:02] [Server thread/INFO]: [SkQuery] Disabling SkQuery v4.1.8
[12:12:02] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling SkQuery v4.1.8 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.w00tmast3r.skquery.SkQuery.onDisable(SkQuery.java:45) ~[SkQuery-4.1.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:196) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:574) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:485) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:207) ~[purpur-1.19.3.jar:git-Purpur-1927]
	at com.w00tmast3r.skquery.elements.events.EvtLambdaWhen.<clinit>(EvtLambdaWhen.java:24) ~[SkQuery-4.1.8.jar:?]
	... 16 more```

**Comment by TheLimeGlass** [comment]
Fixed in 4.1.9
