### ISSUE TITLE
Script options: use permissions

### ISSUE THREAD

**Issue by SanteriPit** [SkQuery/SkQuery#150]
When I try to use permissions in a skript file, it gives me a "severe error"

The error happens when I try to use permissions in a skript like this:
```
script options:
    $ use permissions
```
The skript doesn't need anything else, just that.

**Information:**
- Skript version: 2.6.4
- Server software: Spigot
- Server version: 1.19.2
- Other addons: SkBee (tried without it)

Error:
```
[16:08:38] [Server thread/ERROR]: #!#! 
[16:08:38] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[16:08:38] [Server thread/ERROR]: #!#! 
[16:08:38] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[16:08:38] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:08:38] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[16:08:38] [Server thread/ERROR]: #!#! Here is full list of them:
[16:08:38] [Server thread/ERROR]: #!#! SkQuery v4.1.9 
[16:08:38] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[16:08:38] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[16:08:38] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[16:08:38] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[16:08:38] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[16:08:38] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[16:08:38] [Server thread/ERROR]: #!#! 
[16:08:38] [Server thread/ERROR]: #!#! Stack trace:
[16:08:38] [Server thread/ERROR]: #!#! java.lang.NoSuchMethodError: 'org.skriptlang.skript.lang.script.Script ch.njol.skript.lang.parser.ParserInstance.getCurrentScript()'
[16:08:38] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.elements.effects.base.Pragma.init(Pragma.java:24)
[16:08:38] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.elements.effects.base.OptionsPragma.init(OptionsPragma.java:19)
[16:08:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:255)
[16:08:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[16:08:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:60)
[16:08:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[16:08:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[16:08:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[16:08:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[16:08:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[16:08:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[16:08:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[16:08:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:169)
[16:08:38] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:08:38] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[16:08:38] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:833)
[16:08:38] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[16:08:38] [Server thread/ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:298)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:282)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1940)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1905)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:68)
[16:08:38] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(SourceFile:18)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017)
[16:08:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293)
[16:08:38] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[16:08:38] [Server thread/ERROR]: #!#! 
[16:08:38] [Server thread/ERROR]: #!#! Version Information:
[16:08:38] [Server thread/ERROR]: #!#!   Skript: 2.6.4 (latest)
[16:08:38] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[16:08:38] [Server thread/ERROR]: #!#!     Date: 17:14:25.041218900
[16:08:38] [Server thread/ERROR]: #!#!   Bukkit: 1.19.2-R0.1-SNAPSHOT
[16:08:38] [Server thread/ERROR]: #!#!   Minecraft: 1.19.2
[16:08:38] [Server thread/ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[16:08:38] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.19.0-41-generic
[16:08:38] [Server thread/ERROR]: #!#! 
[16:08:38] [Server thread/ERROR]: #!#! Server platform: Spigot
[16:08:38] [Server thread/ERROR]: #!#! 
[16:08:38] [Server thread/ERROR]: #!#! Current node: null
[16:08:38] [Server thread/ERROR]: #!#! Current item: null
[16:08:38] [Server thread/ERROR]: #!#! 
[16:08:38] [Server thread/ERROR]: #!#! Thread: Server thread
[16:08:38] [Server thread/ERROR]: #!#! 
[16:08:38] [Server thread/ERROR]: #!#! Language: english
[16:08:38] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[16:08:38] [Server thread/ERROR]: #!#! 
[16:08:38] [Server thread/ERROR]: #!#! End of Error.
[16:08:38] [Server thread/ERROR]: #!#! 
```

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/SkQuery/SkQuery/issues/153
