### ISSUE TITLE
Can't use permissions

### ISSUE THREAD

**Issue by DuomaxAE** [SkQuery/SkQuery#153]
whenever I try to use permissions in skript with SkQuery, an error occurs.
This is the error it shows, and yes, I'm sure it's from SkQuery, it only fixes when I remove it:
[12:36:55 ERROR]: #!#! 
[12:36:55 ERROR]: #!#! [Skript] Severe Error:
[12:36:55 ERROR]: #!#! 
[12:36:55 ERROR]: #!#! Something went horribly wrong with Skript.
[12:36:55 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:36:55 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[12:36:55 ERROR]: #!#! Here is full list of them:
[12:36:55 ERROR]: #!#! SkBee v2.12.0 (https://github.com/ShaneBeee/SkBee) Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/) SkQuery v4.1.9 
[12:36:55 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[12:36:55 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[12:36:55 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[12:36:55 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[12:36:55 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[12:36:55 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[12:36:55 ERROR]: #!#! 
[12:36:55 ERROR]: #!#! Stack trace:
[12:36:55 ERROR]: #!#! java.lang.NoSuchMethodError: 'org.skriptlang.skript.lang.script.Script ch.njol.skript.lang.parser.ParserInstance.getCurrentScript()'
[12:36:55 ERROR]: #!#!     at SkQuery-4.1.9 (1).jar//com.w00tmast3r.skquery.elements.effects.base.Pragma.init(Pragma.java:24)
[12:36:55 ERROR]: #!#!     at SkQuery-4.1.9 (1).jar//com.w00tmast3r.skquery.elements.effects.base.OptionsPragma.init(OptionsPragma.java:19)
[12:36:55 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:255)
[12:36:55 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[12:36:55 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[12:36:55 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[12:36:55 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[12:36:55 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[12:36:55 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[12:36:55 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[12:36:55 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[12:36:55 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[12:36:55 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:169)
[12:36:55 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:36:55 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[12:36:55 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:929)
[12:36:55 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[12:36:55 ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[12:36:55 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:322)
[12:36:55 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:306)
[12:36:55 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2297)
[12:36:55 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2257)
[12:36:55 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[12:36:55 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[12:36:55 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:36:55 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:36:55 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[12:36:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1342)
[12:36:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[12:36:55 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[12:36:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1319)
[12:36:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1312)
[12:36:55 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:36:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1290)
[12:36:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1178)
[12:36:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[12:36:55 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[12:36:55 ERROR]: #!#! 
[12:36:55 ERROR]: #!#! Version Information:
[12:36:55 ERROR]: #!#!   Skript: 2.6.4 (latest)
[12:36:55 ERROR]: #!#!     Flavor: skriptlang-github
[12:36:55 ERROR]: #!#!     Date: 17:14:25.041218900
[12:36:55 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[12:36:55 ERROR]: #!#!   Minecraft: 1.19.4
[12:36:55 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[12:36:55 ERROR]: #!#!   OS: Linux amd64 5.19.0-43-generic
[12:36:55 ERROR]: #!#! 
[12:36:55 ERROR]: #!#! Server platform: Paper
[12:36:55 ERROR]: #!#! 
[12:36:55 ERROR]: #!#! Current node: null
[12:36:55 ERROR]: #!#! Current item: null
[12:36:55 ERROR]: #!#! 
[12:36:55 ERROR]: #!#! Thread: Server thread
[12:36:55 ERROR]: #!#! 
[12:36:55 ERROR]: #!#! Language: english
[12:36:55 ERROR]: #!#! Link parse mode: DISABLED
[12:36:55 ERROR]: #!#! 
[12:36:55 ERROR]: #!#! End of Error.
[12:36:55 ERROR]: #!#! 

**To Reproduce**
I wrote this skript:
script options:
    $ use permissions
on right click:
	loop all players:
		if loop-player's tool is paper of mending 1 named "&4&l/fly perms":
			add sk.fly to loop-player's permissions
			remove 1 paper of mending 1 named "&4&l/fly perms" from loop-player's inventory
and then it showed that error
**Information:**
- Skript version: 2.6.4
- Server software: Paper
- Server version: 1.19.4

**Additional context**
There is no other plugin on the server, it was only skript.

**Comment by TheLimeGlass** [comment]
Fixed in 4.1.10
