### ISSUE TITLE
Operation not allowed after ResultSet closed

### ISSUE THREAD

**Issue by DexterSK** [SkQuery/SkQuery#157]
**Describe the bug**
```[14:03:48 WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[14:03:48 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
[14:03:48 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
[14:03:48 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
[14:03:48 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
[14:03:48 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.checkClosed(ResultSetImpl.java:485)
[14:03:48 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.next(ResultSetImpl.java:1802)
[14:03:48 WARN]:        at SkQuery-4.1.10.jar//com.w00tmast3r.skquery.elements.expressions.ExprSQLQueryObjects.get(ExprSQLQueryObjects.java:35)
[14:03:48 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101)
[14:03:48 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:272)
[14:03:48 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[14:03:48 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[14:03:48 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[14:03:48 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[14:03:48 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:312)
[14:03:48 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:277)
[14:03:48 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:282)
[14:03:48 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:193)
[14:03:48 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:152)
[14:03:48 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[14:03:48 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[14:03:48 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:03:48 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[14:03:48 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[14:03:48 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[14:03:48 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2368)
[14:03:48 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2352)
[14:03:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[14:03:48 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:03:48 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:03:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:03:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:03:48 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1366)
[14:03:48 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[14:03:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[14:03:48 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1343)
[14:03:48 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1336)
[14:03:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:03:48 WARN]:        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1314)
[14:03:48 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[14:03:48 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[14:03:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)```

**To Reproduce**
```
command /test:
  trigger:

    set {_result::*} to objects in column "name" from result of query "SELECT name FROM `table` ORDER BY `column` DESC LIMIT 3 OFFSET 0;"
    message "%{_result::*}%"

```

**Information:**
- Skript version: 2.7.0-beta1
- Server software: Purpur
- Server version: 1.20.1

**Additional context**

**Comment by gfrancov** [comment]
Same!!

**Comment by Xgabi86** [comment]
same

**Comment by DexterSK** [comment]
> same

lmao its almost one year old post xD i think we have to fix this yourself
