### ISSUE TITLE
Could not pass event PlayerQuitEvent to SkQuery v4.1.10

### ISSUE THREAD

**Issue by ninjaguardian** [SkQuery/SkQuery#168]
**Describe the bug**
When a player is kicked or banned or anything that is not the disconnect button, the error bellow shows.
**To Reproduce**
Steps to reproduce the behavior if there are any.

**Information:**
- Skript version: 2.7.2
- Server software: paper
- Server version: 1.20.1

**Additional context**
Add any other context about the bug here.
`[14:57:56] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to SkQuery v4.1.10
--
778 | java.lang.NullPointerException: attachment
779 | at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
780 | at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.removeAttachment(LuckPermsPermissible.java:266) ~[?:?]
781 | at org.bukkit.craftbukkit.v1_20_R1.entity.CraftHumanEntity.removeAttachment(CraftHumanEntity.java:263) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
782 | at com.w00tmast3r.skquery.skript.PermissionsHandler.onQuit(PermissionsHandler.java:44) ~[SkQuery-4.1.10.jar:?]
783 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor467.execute(Unknown Source) ~[?:?]
784 | at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
785 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-"f042be6"]
786 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
787 | at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
788 | at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
789 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
790 | at net.minecraft.server.players.PlayerList.remove(PlayerList.java:607) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
791 | at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2178) ~[?:?]
792 | at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:535) ~[?:?]
793 | at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:368) ~[?:?]
794 | at net.minecraft.network.Connection.tick(Connection.java:602) ~[?:?]
795 | at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
796 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1586) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
797 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
798 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
799 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
800 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
801 | at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by TheLimeGlass** [comment]
Fixed in 4.2.0
