### ISSUE TITLE
Problem with MySQL

### ISSUE THREAD

**Issue by Creaous** [SkQuery/SkQuery#47]
_**Running Minecraft Version:**_ 1.15.2
_**Running Skript Version:**_ 2.5-alpha5
_**Running SkQuery Version:**_ 4.1.2

Problem:
Unable to start the script. It returns with java.lang.NullPointerException.

**Error Log:** https://pastebin.com/sDjPWwMh
**Script Content:** https://pastebin.com/7wmsJxp8

Thanks!

**Comment by MineCityZolii** [comment]
Same 
[16:45:27 ERROR]: #!#!
[16:45:27 ERROR]: #!#! [Skript] Severe Error:
[16:45:27 ERROR]: #!#! Could not load sql.sk
[16:45:27 ERROR]: #!#!
[16:45:27 ERROR]: #!#! Something went horribly wrong with Skript.
[16:45:27 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:45:27 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[16:45:27 ERROR]: #!#! Here is full list of them:
[16:45:27 ERROR]: #!#! skRayFall (https://sk.rayfall.net/) Skungee TuSKe (github.com/Tuke-Nuke/TuSKe) SkQuery Skellett (https://forums.skunity.com/resources/skellett.24/) skript-db
[16:45:27 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[16:45:27 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[16:45:27 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[16:45:27 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[16:45:27 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[16:45:27 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[16:45:27 ERROR]: #!#!
[16:45:27 ERROR]: #!#! Stack trace:
[16:45:27 ERROR]: #!#! java.lang.NullPointerException
[16:45:27 ERROR]: #!#!     at com.w00tmast3r.skquery.sql.ScriptCredentials.get(ScriptCredentials.java:50)
[16:45:27 ERROR]: #!#!     at com.w00tmast3r.skquery.sql.ScriptCredentials.get(ScriptCredentials.java:43)
[16:45:27 ERROR]: #!#!     at com.w00tmast3r.skquery.sql.ScriptCredentials.setURL(ScriptCredentials.java:17)
[16:45:27 ERROR]: #!#!     at com.w00tmast3r.skquery.elements.effects.EffOptionSQLURL.register(EffOptionSQLURL.java:21)
[16:45:27 ERROR]: #!#!     at com.w00tmast3r.skquery.elements.effects.base.Pragma.init(Pragma.java:24)
[16:45:27 ERROR]: #!#!     at com.w00tmast3r.skquery.elements.effects.base.OptionsPragma.init(OptionsPragma.java:18)
[16:45:27 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
[16:45:27 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[16:45:27 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[16:45:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1006)
[16:45:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:693)
[16:45:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:409)
[16:45:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:428)
[16:45:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:472)
[16:45:27 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:183)
[16:45:27 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:45:27 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[16:45:27 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761)
[16:45:27 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1866)
[16:45:27 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1674)
[16:45:27 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[16:45:27 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[16:45:27 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[16:45:27 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[16:45:27 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[16:45:27 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[16:45:27 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[16:45:27 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105)
[16:45:27 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098)
[16:45:27 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[16:45:27 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059)
[16:45:27 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974)
[16:45:27 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[16:45:27 ERROR]: #!#!
[16:45:27 ERROR]: #!#! Version Information:
[16:45:27 ERROR]: #!#!   Skript: 2.4.1 (latest)
[16:45:27 ERROR]: #!#!     Flavor: skriptlang-github
[16:45:27 ERROR]: #!#!     Date: 2019-12-22
[16:45:27 ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT
[16:45:27 ERROR]: #!#!   Minecraft: 1.15.2
[16:45:27 ERROR]: #!#!   Java: 1.8.0_261 (Java HotSpot(TM) 64-Bit Server VM 25.261-b12)
[16:45:27 ERROR]: #!#!   OS: Windows Server 2016 amd64 10.0
[16:45:27 ERROR]: #!#!
[16:45:27 ERROR]: #!#! Server platform: Paper
[16:45:27 ERROR]: #!#!
[16:45:27 ERROR]: #!#! Current node: $ db url jdbc:mysql://localhost:3306/minecraft (sql.sk, line 3)
[16:45:27 ERROR]: #!#! Current item: null
[16:45:27 ERROR]: #!#!
[16:45:27 ERROR]: #!#! Thread: Server thread
[16:45:27 ERROR]: #!#!
[16:45:27 ERROR]: #!#! Language: english
[16:45:27 ERROR]: #!#! Link parse mode: DISABLED
[16:45:27 ERROR]: #!#!
[16:45:27 ERROR]: #!#! End of Error.
[16:45:27 ERROR]: #!#!

**Comment by TheLimeGlass** [comment]
Fixed in 4.1.3
