### ISSUE TITLE
Big error in console when register a n ew shapeless recipe

### ISSUE THREAD

**Issue by CommanderDonkey** [SkQuery/SkQuery#56]
**Describe the bug**
When i load the script, an error appears in the console

**To Reproduce**
Paste the Code and load the script

**Information:**
- Skript version: 2.5
- Server software: git-Paper-206
- Server version: 1.16.3

**Script**
on script load:
  wipe server crafting recipes
  register new shapeless recipe for piglin banner pattern named "&cBandage" using string, paper, string, paper, string, paper, string, paper, string

**Error**
[15:46:26 WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[15:46:26 WARN]:        at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:29)
[15:46:26 WARN]:        at com.w00tmast3r.skquery.elements.effects.EffNewRecipe.execute(EffNewRecipe.java:43)
[15:46:26 WARN]:        at ch.njol.skript.lang.Effect.run(Effect.java:52)
[15:46:26 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[15:46:26 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[15:46:26 WARN]:        at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[15:46:26 WARN]:        at ch.njol.skript.events.EvtScript.register(EvtScript.java:61)
[15:46:26 WARN]:        at ch.njol.skript.ScriptLoader$4.call(ScriptLoader.java:738)
[15:46:26 WARN]:        at ch.njol.skript.ScriptLoader$4.call(ScriptLoader.java:1)
[15:46:26 WARN]:        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:761)
[15:46:26 WARN]:        at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:402)
[15:46:26 WARN]:        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:421)
[15:46:26 WARN]:        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:465)
[15:46:26 WARN]:        at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:977)
[15:46:26 WARN]:        at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:186)
[15:46:26 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:46:26 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[15:46:26 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1908)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[15:46:26 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[15:46:26 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by TheLimeGlass** [comment]
Duplicate #5
