### ISSUE TITLE
Permission System doesnt save Permissions

### ISSUE THREAD

**Issue by OfflinePing** [SkQuery/SkQuery#68]
**Describe the bug**
I made a command /rank to give users a rank. U can only execute it with Admin permission. if i have admin permission, and give myself something premium, admin gets removed and i get premium so i cant execute that same command again. after i rejoin i have admin again?!

**To Reproduce**
Steps to reproduce the behavior if there are any.

**Information:**
- Skript version: 2.2-dev25
- Server software: git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
- Server version: 1.8.8

**Additional context**
my Code:
```Options:
    P: &7× &9CloudMC &7×
    Owner: "CloudF0rce"
    Invalid: "&7× &9CloudMC &7× &cInvalid Command"
    Admin: "cm.Admin"
    Mod: "cm.Mod"
    Prem: "cm.Premium"
    Player: "cm.Player"
    NoPerm: "&7× &9CloudMC &7× &cNo Permissions"
 
script options:
    $ use permissions
 
command /rank [<offlineplayer>] [<text>]:
    trigger:
        if player has permission {@Admin}:
            if arg 1 and arg 2 is set:
                if arg-2 is "Admin":
                    if arg-1 has permission {@Mod}:
                        remove {@Mod} from arg-1's permissions
                    if arg-1 has permission {@Prem}:
                        remove {@Prem} from arg-1's permissions
                    if arg-1 has permission {@Player}:
                        remove {@Player} from arg-1's permissions
                    add {@Admin} to arg-1's permissions
                    broadcast "{@P} The Player &a%arg-1%&7 is now &cAdmin"
                if arg-2 is "Mod" or "Moderator":
                    if arg-1 has permission {@Admin}:
                        remove {@Admin} from arg-1's permissions
                    if arg-1 has permission {@Prem}:
                        remove {@Prem} from arg-1's permissions
                    if arg-1 has permission {@Player}:
                        remove {@Player} from arg-1's permissions
                    add {@Mod} to arg-1's permissions
                    broadcast "{@P} The Player &a%arg-1%&7 is now &bMod"
                if arg-2 is "Premium" or "Prem":
                    if arg-1 has permission {@Mod}:
                        remove {@Mod} from arg-1's permissions
                    if arg-1 has permission {@Admin}:
                        remove {@Admin} from arg-1's permissions
                    if arg-1 has permission {@Player}:
                        remove {@Player} from arg-1's permissions
                    add {@Admin} to arg-1's permissions
                    broadcast "{@P} The Player &a%arg-1%&7 is now &ePremium"
                if arg-2 is "Player":
                    if arg-1 has permission {@Mod}:
                        remove {@Mod} from arg-1's permissions
                    if arg-1 has permission {@Admin}:
                        remove {@Admin} from arg-1's permissions
                    if arg-1 has permission {@Prem}:
                        remove {@Prem} from arg-1's permissions
                    add {@Player} to arg-1's permissions
                    broadcast "{@P} The Player &a%arg-1%&7 is now &ePremium"
        else:
            send {@NoPerm}
 
on join:
    set join message to "{@P} &7%player% joined"
    heal the player
    set hunger bar of player to 20
    clear player's inventory
    teleport player to {Spawn}
    if player has permission {@Player}:
        set player tab name to "&7Player ┃ %player%"
    if player has permission {@Prem}:
        set player tab name to "&ePremium &7┃ %player%"
    if player has permission {@Mod}:
        set player tab name to "&bMod &7┃ %player%"
    if player has permission {@Admin}:
        set player tab name to "&cAdmin &7┃ %player%"
```
        
        Sometimes i get this Error
```[19:58:51 ERROR]: Could not pass event PlayerQuitEvent to SkQuery v3.21.4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:364) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:875) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.disconnect(PlayerConnection.java:186) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.CommandKick.execute(SourceFile:50) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:123) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:44) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_281]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.IllegalArgumentException: Attachment cannot be null
        at org.bukkit.permissions.PermissibleBase.removeAttachment(PermissibleBase.java:131) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.removeAttachment(CraftHumanEntity.java:126) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at com.w00tmast3r.skquery.skript.PermissionsHandler.onQuit(PermissionsHandler.java:44) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 25 more
 ```
  Maybe it helps

**Comment by TheLimeGlass** [comment]
SkQuery doesn't keep track of permissions, that's what the user is suppose to do with variables.

**Comment by TheLimeGlass** [comment]
SkQuery doesn't have permissions syntaxes, it's in Skript now
