### ISSUE TITLE
WARNING Console Spam

### ISSUE THREAD

**Issue by mrniceguy051** [SkQuery/SkQuery#73]
This is happening in my console, and I don't know why.

`>.... [16:11:43 WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
>.... [16:11:43 WARN]: at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
>.... [16:11:43 WARN]: at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
>.... [16:11:43 WARN]: at com.w00tmast3r.skquery.elements.effects.EffOptionThread$1.run(EffOptionThread.java:44)
>.... [16:11:43 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
>.... [16:11:43 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
>.... [16:11:43 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1426)
>.... [16:11:43 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419)
>.... [16:11:43 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1341)
>.... [16:11:43 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129)
>.... [16:11:43 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
>.... [16:11:43 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
>.... [16:11:43 WARN]: Caused by: java.lang.NullPointerException
>.... [16:11:43 WARN]: at jdk.internal.reflect.GeneratedMethodAccessor237.invoke(Unknown Source)
>.... [16:11:43 WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [16:11:43 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>.... [16:11:43 WARN]: at com.w00tmast3r.skquery.elements.effects.EffOptionThread$2.call(EffOptionThread.java:62)
>.... [16:11:43 WARN]: at com.w00tmast3r.skquery.elements.effects.EffOptionThread$2.call(EffOptionThread.java:59)
>.... [16:11:43 WARN]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>.... [16:11:43 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>.... [16:11:43 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>.... [16:11:43 WARN]: ... 1 more
>.... [16:11:44 WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
>.... [16:11:44 WARN]: at com.w00tmast3r.skquery.elements.effects.EffOptionThread$1.run(EffOptionThread.java:44)
>.... [16:11:44 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
>.... [16:11:44 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1426)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1341)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
>.... [16:11:44 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
>.... [16:11:44 WARN]: Caused by: java.lang.NullPointerException
>.... [16:11:44 WARN]: at jdk.internal.reflect.GeneratedMethodAccessor237.invoke(Unknown Source)
>.... [16:11:44 WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [16:11:44 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>.... [16:11:44 WARN]: at com.w00tmast3r.skquery.elements.effects.EffOptionThread$2.call(EffOptionThread.java:62)
>.... [16:11:44 WARN]: at com.w00tmast3r.skquery.elements.effects.EffOptionThread$2.call(EffOptionThread.java:59)
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>.... [16:11:44 WARN]: ... 1 more
>.... [16:11:44 WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
>.... [16:11:44 WARN]: at com.w00tmast3r.skquery.elements.effects.EffOptionThread$1.run(EffOptionThread.java:44)
>.... [16:11:44 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
>.... [16:11:44 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1426)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1341)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
>.... [16:11:44 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
>.... [16:11:44 WARN]: Caused by: java.lang.NullPointerException
>.... [16:11:44 WARN]: at jdk.internal.reflect.GeneratedMethodAccessor237.invoke(Unknown Source)
>.... [16:11:44 WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [16:11:44 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>.... [16:11:44 WARN]: at com.w00tmast3r.skquery.elements.effects.EffOptionThread$2.call(EffOptionThread.java:62)
>.... [16:11:44 WARN]: at com.w00tmast3r.skquery.elements.effects.EffOptionThread$2.call(EffOptionThread.java:59)
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>.... [16:11:44 WARN]: ... 1 more
>.... [16:11:44 WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
>.... [16:11:44 WARN]: at com.w00tmast3r.skquery.elements.effects.EffOptionThread$1.run(EffOptionThread.java:44)
>.... [16:11:44 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
>.... [16:11:44 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1426)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1341)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129)
>.... [16:11:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
>.... [16:11:44 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
>.... [16:11:44 WARN]: Caused by: java.lang.NullPointerException
>.... [16:11:44 WARN]: at jdk.internal.reflect.GeneratedMethodAccessor237.invoke(Unknown Source)
>.... [16:11:44 WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [16:11:44 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>.... [16:11:44 WARN]: at com.w00tmast3r.skquery.elements.effects.EffOptionThread$2.call(EffOptionThread.java:62)
>.... [16:11:44 WARN]: at com.w00tmast3r.skquery.elements.effects.EffOptionThread$2.call(EffOptionThread.java:59)
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>.... [16:11:44 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>.... [16:11:44 WARN]: ... 1 more`

**Comment by TheLimeGlass** [comment]
What Skript version... What Skquery version... What are you doing with the $ thread option...
