### ISSUE TITLE
Entity Pathfind causes errors

### ISSUE THREAD

**Issue by DrakDragon** [SkQuery/SkQuery#80]
Dunno what changed, this used to work but I updated versions of both server and plugins and then all of a sudden "make entity pathfind" stopped working.

command /tfollow:
  trigger:
    loop entities in radius 4 of player:
      make loop-entity pathfind to location of player at speed 1.0

Expected result: 
The loop-entity moves to the player

Result:
Fails with "An internal error occurred while attempting to perform this command." and the log gives the error below.

Note: I have tried updating everything, all my plugins are on the latest version and whatnot. I am not sure what happened.

Output from Server
[15:10:44] [Server thread/INFO]: Brognar [66c23840-f1fe-4b0b-aa3d-612188527594]: /tfollow
[15:10:44] [Server thread/ERROR]: #!#! 
[15:10:44] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[15:10:44] [Server thread/ERROR]: #!#! 
[15:10:44] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[15:10:44] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:10:44] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:10:44] [Server thread/ERROR]: #!#! Here is full list of them:
[15:10:44] [Server thread/ERROR]: #!#! skRayFall v1.9.26 (https://sk.rayfall.net/) Quarsk v1.3 Khoryl v1.0.3 SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee) skDragon v0.17 SkQuery v4.1.5 Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/) skript-votifier-hook v1.1.0 skript-logs v0.1.3 (https://github.com/Blueyescat/skript-logs) 
[15:10:44] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[15:10:44] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:10:44] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:10:44] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:10:44] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:10:44] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:10:44] [Server thread/ERROR]: #!#! 
[15:10:44] [Server thread/ERROR]: #!#! Stack trace:
[15:10:44] [Server thread/ERROR]: #!#! java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.EntityInsentient
[15:10:44] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.util.Reflection.getNMSClass(Reflection.java:16)
[15:10:44] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.elements.effects.EffPathfind.execute(EffPathfind.java:40)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:289)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:258)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:175)
[15:10:44] [Server thread/ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[15:10:44] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[15:10:44] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:10:44] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2162)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1458)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[15:10:44] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[15:10:44] [Server thread/ERROR]: #!#! Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.EntityInsentient
[15:10:44] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[15:10:44] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[15:10:44] [Server thread/ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[15:10:44] [Server thread/ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[15:10:44] [Server thread/ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:375)
[15:10:44] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.util.Reflection.getNMSClass(Reflection.java:14)
[15:10:44] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.elements.effects.EffPathfind.execute(EffPathfind.java:40)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:289)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:258)
[15:10:44] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:175)
[15:10:44] [Server thread/ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[15:10:44] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[15:10:44] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:10:44] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2162)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1458)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[15:10:44] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[15:10:44] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[15:10:44] [Server thread/ERROR]: #!#! 
[15:10:44] [Server thread/ERROR]: #!#! Version Information:
[15:10:44] [Server thread/ERROR]: #!#!   Skript: 2.6-beta2 (latest)
[15:10:44] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[15:10:44] [Server thread/ERROR]: #!#!     Date: 08:57:41.422360
[15:10:44] [Server thread/ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[15:10:44] [Server thread/ERROR]: #!#!   Minecraft: 1.17.1
[15:10:44] [Server thread/ERROR]: #!#!   Java: 16.0.1 (OpenJDK 64-Bit Server VM 16.0.1+9)
[15:10:44] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.10.0-1160.25.1.el7.x86_64
[15:10:44] [Server thread/ERROR]: #!#! 
[15:10:44] [Server thread/ERROR]: #!#! Server platform: Paper
[15:10:44] [Server thread/ERROR]: #!#! 
[15:10:44] [Server thread/ERROR]: #!#! Current node: null
[15:10:44] [Server thread/ERROR]: #!#! Current item: pathfind
[15:10:44] [Server thread/ERROR]: #!#! Current trigger: command /tfollow (simple event) (oddities.sk, line 59)
[15:10:44] [Server thread/ERROR]: #!#! 
[15:10:44] [Server thread/ERROR]: #!#! Thread: Server thread
[15:10:44] [Server thread/ERROR]: #!#! 
[15:10:44] [Server thread/ERROR]: #!#! Language: english
[15:10:44] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[15:10:44] [Server thread/ERROR]: #!#! 
[15:10:44] [Server thread/ERROR]: #!#! End of Error.
[15:10:44] [Server thread/ERROR]: #!#!

**Comment by Jeremylo1** [comment]
Indeed I have the same problem in a different context.

Basically, the llama is no longer considered alive after the first execution. The skript executes the `broacast "test"` only once

```
on spawn of llama:
    wait 1 tick
    if display name of entity is "TEST":
        while entity is alive:
            wait 3 ticks
            make entity pathfind to location at 84.5, 63.5, 109.5 in world "world" with speed 3.5
                        broacast "test"
```

Yet it works very well here:

```
on spawn of llama:
    wait 1 tick
    if display name of entity is "TEST":
        while entity is alive:
            wait 3 ticks
            broacast "test"
```
`make entity pathfind` seems to break something

Skript : 2.6-beta2
Serveur : Purpur-1327 (1.17.1)

The problem is not present with skript 2.5.3 in Paper 1.16.5

**Comment by MrZomka** [comment]
Still not fixed :/

**Comment by TheLimeGlass** [comment]
Pathfinding is now in vanilla Skript using Paper.
