### ISSUE TITLE
Error occurred while enabling SkQuery

### ISSUE THREAD

**Issue by dzerky** [SkQuery/SkQuery#97]
**Describe the bug**
I tried to enable all SkQuery versions, from 4.1.5 to 4.1.1, all of them returned:

**To Reproduce**
[17:36:46] [Server thread/INFO]: [SkQuery] Enabling SkQuery v4.1.5
[17:36:46] [Server thread/INFO]: [skQuery] Locating classes from SkQuery...
[17:36:47] [Server thread/ERROR]: Fatal error trying to convert SkQuery v4.1.5:javassist/util/HotSwapper$1.class
java.lang.ArrayIndexOutOfBoundsException: null
[17:36:47] [Server thread/ERROR]: Error occurred while enabling SkQuery v4.1.5 (Is it up to date?)
java.lang.ClassFormatError: Truncated class file
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:193) ~[server.jar:3284a-Spigot-3892929-0ab8487]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[server.jar:3284a-Spigot-3892929-0ab8487]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[server.jar:3284a-Spigot-3892929-0ab8487]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at com.w00tmast3r.skquery.Registration.enableSnooper(Registration.java:52) ~[?:?]
	at com.w00tmast3r.skquery.SkQuery.onEnable(SkQuery.java:30) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:3284a-Spigot-3892929-0ab8487]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3284a-Spigot-3892929-0ab8487]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3284a-Spigot-3892929-0ab8487]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:520) ~[server.jar:3284a-Spigot-3892929-0ab8487]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:434) ~[server.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619) ~[server.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[server.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[server.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[server.jar:3284a-Spigot-3892929-0ab8487]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Information:**
- Skript version: 2.6
- Server software: Paper
- Server version: 1.17

**Comment by TheLimeGlass** [comment]
What version of Java are you using?

**Comment by dzerky** [comment]
I use version 1.16.

**Comment by dzerky** [comment]
> What version of Java are you using?

I use java version 1.16.

**Comment by dzerky** [comment]
And I use ViaVersion. If it can't be that.

**Comment by TitanDevX** [comment]
Same error

**Comment by TheLimeGlass** [comment]
Potentially a virus version of SkQuery, modified version of SKQuery are out on the internet. Only download from https://github.com/SkQuery/SkQuery/releases and the SkUnity/Spigot pages that redirect to the github releases page.
