### ISSUE TITLE
Error occurred while enabling SkQuery

### ISSUE THREAD

**Issue by GalaxyCrafted** [SkQuery/SkQuery#99]
**Describe the bug**
Same thing with SKQuery 4.1.6 and 4.1.4

[21:42:35] [Server thread/ERROR]: Error occurred while enabling SkQuery v4.1.5 (Is it up to date?)
java.lang.ClassFormatError: Truncated class file
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:855) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:753) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:573) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[paper.jar:git-Paper-404]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper.jar:git-Paper-404]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at com.w00tmast3r.skquery.Registration.enableSnooper(Registration.java:52) ~[SkQuery-4.1.5.jar:?]
	at com.w00tmast3r.skquery.SkQuery.onEnable(SkQuery.java:30) ~[SkQuery-4.1.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper.jar:git-Paper-404]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper.jar:git-Paper-404]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper.jar:git-Paper-404]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper.jar:git-Paper-404]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper.jar:git-Paper-404]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[paper.jar:git-Paper-404]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[paper.jar:git-Paper-404]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper.jar:git-Paper-404]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper.jar:git-Paper-404]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[21:42:35] [Server thread/INFO]: [SkQuery] Disabling SkQuery v4.1.5
[21:42:35] [Server thread/ERROR]: Error occurred while disabling SkQuery v4.1.5 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.w00tmast3r.skquery.SkQuery.onDisable(SkQuery.java:39) ~[SkQuery-4.1.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper.jar:git-Paper-404]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper.jar:git-Paper-404]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper.jar:git-Paper-404]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper.jar:git-Paper-404]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper.jar:git-Paper-404]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper.jar:git-Paper-404]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper.jar:git-Paper-404]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[paper.jar:git-Paper-404]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[paper.jar:git-Paper-404]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper.jar:git-Paper-404]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper.jar:git-Paper-404]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[paper.jar:git-Paper-404]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227) ~[paper.jar:git-Paper-404]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[paper.jar:git-Paper-404]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:207) ~[paper.jar:git-Paper-404]
	at com.w00tmast3r.skquery.elements.events.EvtLambdaWhen.<clinit>(EvtLambdaWhen.java:24) ~[SkQuery-4.1.5.jar:?]
	... 13 more

**Information:**
- Skript version: 2.6.1
- Server software: PaperSpigot
- Server version: 1.17.1
- Java Version : 17

**Comment by TheLimeGlass** [comment]
Duplicate #97
